### ISSUE TITLE
Start Action keeps hanging

### ISSUE THREAD

**Issue by rawlingssam** [aquasecurity/tracee-action#49]
Below is a console log from GitHub Actions. For unknown reason, Tracee keeps hanging.

15m 52s
[87](https://github.com/org-name/ui-library/actions/runs/5177811208/jobs/9328864463#step:2:87)
Waiting for Tracee to start....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................

**Comment by zMynxx** [comment]
As a continuous to this issue, I had encountered the same issue. I did however, managed to rollback to 0.2.0 and run it successfully in a github workflow.

Steps to reproduce:
- Make sure to have checkout actions prior to running -start tracee action.
- Tried and managed to run successfully only on 0.2.0.

Example manifest:
```
---
name: Aqua Tracee Security
on:
  workflow_dispatch:
  # pull_request:
  #   branches:
  #     - main
jobs:
  tracee:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Start Tracee
        uses: aquasecurity/tracee-action@v0.2.0-start

      - name: Run your tests
        run: echo "Run your tests here"

      - name: Stop Tracee
        uses: aquasecurity/tracee-action@v0.2.0-stop
```
