### ISSUE TITLE
properly scope file_writes policy

### ISSUE THREAD

**Issue by itaysk** [aquasecurity/tracee-action#52]
file_writes policy has a global scope and an even filter:

```yaml
scope:
  - global
rules:
  - event: security_file_open
    filter: 
      - args.pathname=$WORKSPACE
```

could this be improved to reduce the scope of the trace before filtering the event?
